=== greciatuatorres/lenguajes-de-marcas/unidad-02/sesion-01-introduccion-xml/universo.dtd
<!ELEMENT universo (heroe+)>
<!ELEMENT heroe (nombre, identidad, habilidades, arma?, equipo)>
<!ATTLIST heroe id ID #REQUIRED>

<!ELEMENT nombre (#PCDATA)>
<!ELEMENT identidad (#PCDATA)>
<!ELEMENT habilidades (habilidad+)>
<!ELEMENT habilidad (#PCDATA)>
<!ELEMENT arma (#PCDATA)>
<!ELEMENT equipo (#PCDATA)>

=== greciatuatorres/lenguajes-de-marcas/unidad-02/sesion-01-introduccion-xml/actividad-final.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE universo SYSTEM "universo.dtd">
<universo>
    <!-- Coleccion de personajes-->
    <heroe id="H01">
        <nombre>Tony Stark</nombre>
        <identidad>Iron Man</identidad>
        <habilidades>
            <habilidad>Inteligencia</habilidad>
            <habilidad>Tecnología</habilidad>
            <habilidad>Liderazgo</habilidad>
        </habilidades>
        <equipo>Vengadores</equipo>
    </heroe>

    <heroe id="H02">
        <nombre>Steve Rogers</nombre>
        <identidad>Capitan America</identidad>
        <habilidades>
            <habilidad>Humano mejorado</habilidad>
            <habilidad>Envejecimiento lento</habilidad>
            <habilidad>Fuerza &amp; resistencia</habilidad>
            <habilidad>Combate cuerpo a cuerpo &amp; táctica</habilidad>
            <habilidad>Liderazgo</habilidad>
        </habilidades>
        <arma>Escudo</arma>
        <equipo>Vengadores</equipo>
    </heroe>

    <heroe id="H03">
        <nombre>Thor Odinson</nombre>
        <identidad>Thor</identidad>
        <habilidades>
            <habilidad>Dios del trueno</habilidad>
            <habilidad>Envejecimiento lento</habilidad>
            <habilidad>Control del trueno</habilidad>
            <habilidad>Control del trueno</habilidad>
            <habilidad>Combate cuerpo a cuerpo</habilidad>
            <habilidad>Liderazgo</habilidad>
        </habilidades>
        <arma>Mjolnir</arma>
        <equipo>Vengadores &amp; guardianes de la galaxia &amp; revengadores</equipo>
    </heroe>
</universo>
